name: Self-hosted runner (push-caller)

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "tests/**"
      - ".github/**"
      - "templates/**"
      - "utils/**"

jobs:
  check-for-setup:
      runs-on: ubuntu-latest
      name: Check if setup was changed
      outputs:
        changed: ${{ steps.was_changed.outputs.changed }}
      steps:
        - uses: actions/checkout@v3
          with: 
            fetch-depth: "2"
        
        - name: Get changed files
          id: changed-files
          uses: tj-actions/changed-files@v22.2
        
        - name: Was setup changed 
          id: was_changed
          run: |
            for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              if [ `basename "${file}"` = "setup.py" ]; then
                echo ::set-output name=changed::"1"
              fi
            done

  build-docker-containers:
    needs: check-for-setup
    if: (github.event_name == 'push') && (needs.check-for-setup.outputs.changed == '1')
    uses: ./.github/workflows/build-docker-images.yml
    secrets: inherit

  run_push_ci:
    name: Run Push CI
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: build-docker-containers
    steps:
      - name: Checkout transformers
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          ssh-key: "${{ secrets.COMMIT_KEY }}"

      - name: Checkout to branch push-ci
        # A more strict way to make sure`push-ci` is exactly the same as `main` at the push event commit.
        run: |
          git checkout -b push-ci
          git push -u origin push-ci --force
